export const TAGS_DATA = [
    {
        name: "typescript",
        displayName: "TypeScript",
        description: "JavaScript with syntax for types.",
        color: "text-blue-600",
        badge: "TS",
        guidelines:
            "Use for TypeScript-specific questions, guides, or insights.",
        about: "TypeScript extends JavaScript by adding types for better tooling and fewer bugs.",
        aboutLink: "https://www.typescriptlang.org",
    },
    {
        name: "webdev",
        displayName: "Web Development",
        description: "Because the internet...",
        color: "text-blue-600",
        badge: "",
        guidelines:
            "Content related to building, optimizing, or deploying websites.",
        about: "Web development encompasses all aspects of building web applications.",
        aboutLink: "https://developer.mozilla.org/en-US/docs/Learn",
    },
    {
        name: "nextjs",
        displayName: "Next.js",
        description: "The React framework for production.",
        color: "text-black",
        badge: "",
        guidelines:
            "For content related to building applications with Next.js.",
        about: "Next.js is a React framework enabling hybrid static and server rendering.",
        aboutLink: "https://nextjs.org",
    },
    {
        name: "docker",
        displayName: "Docker",
        description: "Containerize all the things!",
        color: "text-blue-400",
        badge: "",
        guidelines:
            "Use for topics about Docker containers, images, and best practices.",
        about: "Docker simplifies app deployment by creating lightweight containers.",
        aboutLink: "https://www.docker.com",
    },
    {
        name: "go",
        displayName: "Go",
        description: "A language designed for simplicity and speed.",
        color: "text-cyan-500",
        badge: "GO",
        guidelines: "Use for Go language discussions, guides, and projects.",
        about: "Go is a statically typed, compiled language designed for efficiency.",
        aboutLink: "https://golang.org",
    },
    {
        name: "rust",
        displayName: "Rust",
        description: "Safe, fast, and fearless systems programming.",
        color: "text-orange-500",
        badge: "",
        guidelines:
            "For questions or discussions about Rust programming and performance.",
        about: "Rust is a systems programming language that guarantees memory safety.",
        aboutLink: "https://www.rust-lang.org",
    },
    {
        name: "devops",
        displayName: "DevOps",
        description: "Bridging development and operations.",
        color: "text-indigo-500",
        badge: "",
        guidelines:
            "Use for topics about CI/CD, automation, and infrastructure management.",
        about: "DevOps practices aim to shorten the development lifecycle and improve deployment quality.",
        aboutLink: "https://aws.amazon.com/devops",
    },
    {
        name: "graphql",
        displayName: "GraphQL",
        description: "A query language for APIs.",
        color: "text-pink-600",
        badge: "",
        guidelines:
            "Use for questions and discussions about GraphQL API design and usage.",
        about: "GraphQL is a query language for APIs that allows clients to request exactly what they need.",
        aboutLink: "https://graphql.org",
    },
    {
        name: "firebase",
        displayName: "Firebase",
        description: "Build and scale with Google's backend-as-a-service.",
        color: "text-yellow-500",
        badge: "",
        guidelines:
            "Use for discussions about Firebase authentication, Firestore, hosting, and more.",
        about: "Firebase helps developers build and scale apps without managing backend infrastructure.",
        aboutLink: "https://firebase.google.com",
    },
    {
        name: "javascript",
        displayName: "JavaScript",
        description: "JavaScript is everywhere.",
        color: "text-yellow-600",
        badge: "JS",
        guidelines:
            "Use for JavaScript-related discussions, tutorials, and problem-solving.",
        about: "JavaScript is a versatile scripting language used to create dynamic web content.",
        aboutLink: "https://developer.mozilla.org/en-US/docs/Web/JavaScript",
    },
    {
        name: "react",
        displayName: "React",
        description: "A JavaScript library for building user interfaces.",
        color: "text-blue-500",
        badge: "",
        guidelines:
            "Use for building UI components and applications with React.",
        about: "React is a popular JavaScript library for building interactive UIs.",
        aboutLink: "https://reactjs.org",
    },
    {
        name: "python",
        displayName: "Python",
        description: "A versatile programming language.",
        color: "text-blue-700",
        badge: "PY",
        guidelines:
            "Use for Python programming, tutorials, and problem-solving discussions.",
        about: "Python is a powerful programming language known for its simplicity and readability.",
        aboutLink: "https://www.python.org",
    },
    {
        name: "tailwindcss",
        displayName: "Tailwind CSS",
        description: "A utility-first CSS framework.",
        color: "text-cyan-600",
        badge: "",
        guidelines:
            "Use for Tailwind CSS utility classes, tips, and layout designs.",
        about: "Tailwind CSS is a utility-first framework for rapidly building custom designs.",
        aboutLink: "https://tailwindcss.com",
    },
    {
        name: "css",
        displayName: "CSS",
        description: "Cascading Style Sheets: the styling language of the web.",
        color: "text-pink-500",
        badge: "CSS",
        guidelines:
            "Use for CSS tips, tricks, and problem-solving related to styling web pages.",
        about: "CSS is used to style HTML documents and enhance the presentation of web content.",
        aboutLink: "https://developer.mozilla.org/en-US/docs/Web/CSS",
    },
    {
        name: "html",
        displayName: "HTML",
        description: "The markup language of the web.",
        color: "text-orange-600",
        badge: "HTML",
        guidelines:
            "Use for topics related to HTML syntax, structure, and semantics.",
        about: "HTML is the standard markup language for creating web pages.",
        aboutLink: "https://developer.mozilla.org/en-US/docs/Web/HTML",
    },
    {
        name: "node",
        displayName: "Node.js",
        description: "Server-side JavaScript runtime.",
        color: "text-green-700",
        badge: "",
        guidelines:
            "Use for discussions about Node.js, its packages, and server-side JavaScript development.",
        about: "Node.js allows you to run JavaScript code outside a browser, commonly used for backend services.",
        aboutLink: "https://nodejs.org",
    },
    {
        name: "php",
        displayName: "PHP",
        description: "A popular server-side scripting language.",
        color: "text-indigo-600",
        badge: "PHP",
        guidelines: "Use for PHP syntax, frameworks, and problem-solving.",
        about: "PHP is a widely-used scripting language designed for web development.",
        aboutLink: "https://www.php.net",
    },
    {
        name: "java",
        displayName: "Java",
        description: "Write once, run anywhere.",
        color: "text-red-500",
        badge: "JAVA",
        guidelines:
            "Use for Java-specific questions, frameworks, and backend development.",
        about: "Java is a high-level, object-oriented programming language known for cross-platform capabilities.",
        aboutLink: "https://www.java.com",
    },
    {
        name: "csharp",
        displayName: "C# (C-Sharp)",
        description:
            "A modern object-oriented programming language by Microsoft.",
        color: "text-purple-600",
        badge: "C#",
        guidelines:
            "Use for C# language discussions, .NET framework, and development tips.",
        about: "C# is used for building a variety of applications, including web, desktop, and games.",
        aboutLink: "https://learn.microsoft.com/en-us/dotnet/csharp/",
    },
    {
        name: "vuejs",
        displayName: "Vue.js",
        description: "The progressive JavaScript framework.",
        color: "text-green-500",
        badge: "",
        guidelines:
            "Use for discussions about building interfaces with Vue.js.",
        about: "Vue.js is a progressive JavaScript framework for building user interfaces and SPAs.",
        aboutLink: "https://vuejs.org",
    },
    {
        name: "django",
        displayName: "Django",
        description: "The web framework for perfectionists with deadlines.",
        color: "text-green-700",
        badge: "",
        guidelines:
            "Use for Django framework questions, tips, and best practices.",
        about: "Django is a high-level Python framework for developing robust and scalable web applications.",
        aboutLink: "https://www.djangoproject.com",
    },
    {
        name: "express",
        displayName: "Express.js",
        description:
            "Fast, unopinionated, minimalist web framework for Node.js.",
        color: "text-gray-700",
        badge: "",
        guidelines: "Use for backend development discussions with Express.js.",
        about: "Express is a flexible web application framework for Node.js.",
        aboutLink: "https://expressjs.com",
    },
    {
        name: "backend",
        displayName: "Backend",
        description: "Server-side development practices and technologies.",
        color: "text-gray-700",
        badge: "",
        guidelines:
            "Use for discussions related to server-side logic, APIs, databases, and backend frameworks.",
        about: "Backend development covers server-side logic, databases, APIs, and server architecture.",
        aboutLink: "https://developer.mozilla.org/en-US/docs/Learn/Server-side",
    },
    {
        name: "api",
        displayName: "API",
        description: "Application Programming Interfaces.",
        color: "text-indigo-600",
        badge: "",
        guidelines:
            "Use for API design, development, integration, and best practices.",
        about: "An API allows software components to communicate and interact with each other.",
        aboutLink: "https://developer.mozilla.org/en-US/docs/Web/API",
    },
    {
        name: "programming",
        displayName: "Programming",
        description: "General programming concepts and discussions.",
        color: "text-purple-600",
        badge: "",
        guidelines:
            "Use for general programming concepts, paradigms, and techniques.",
        about: "Programming involves writing instructions for computers to perform specific tasks.",
        aboutLink: "https://en.wikipedia.org/wiki/Computer_programming",
    },
    {
        name: "beginners",
        displayName: "Beginners",
        description: "Helping beginners learn and grow.",
        color: "text-gray-600",
        badge: "",
        guidelines:
            "Use for topics related to learning and growing as a developer.",
        about: "Beginner-friendly content to help you learn and grow as a developer.",
    },
];
